#! /usr/bin/env python

import sys
# import numpy as np
from netCDF4 import num2date
# from trackpart import Euler_Forward
# import ladim
from ladim.grid import Grid
from ladim.forcing import ROMS_forcing
from ladim.release import ParticleReleaser
from ladim.configuration import Configure
from ladim.state import State
from ladim.output import OutPut
# from ladim.behaviour import behaviour

# ==================
# Initiate the model
# ==================

print("Starting LADIM")


# Read the configuration file
# --------------------

if len(sys.argv) > 1:   # configuration file from command line
    config_file = sys.argv[1]
else:
    config_file = 'ladim.yaml'

config = Configure(config_file, loglevel='INFO')

numsteps = config.numsteps
dt = config.dt


# State
state = State(config)

# --------------------
# Input grid and files
# --------------------

grid = Grid(config)

forcing = ROMS_forcing(config, grid)


# tunits = forcing._nc.variables['ocean_time'].units

# ------------
# Initiate grid
# ------------


# ----------------------
# Particle release file
# ----------------------

partini = ParticleReleaser(config, loglevel='INFO')

# ------------------
# Init output file
# -----------------

out = OutPut(config)
# Problem under, får ikke inn multiplisiteten
out.write_particle_variables(partini)

# ==============
# Main time loop
# ==============

for i in range(numsteps+1):

    # Update forcing
    forcing.update(i)

    # Read particles ?
    # unique_steps ikke godt navn eksternt
    if i in partini.unique_steps:
        # Tips: Gjøre begge delet i read_particles
        V = next(partini)
        state.append(V)

    # Save to file
    if i % config.output_period == 0:
        print("Output: i = ", i, num2date(i*dt,
              'seconds since %s' % str(config.start_time)))
        out.write(state)

    # --- Update the model state ---
    state.update(grid, forcing)

    # Individual behaviour
    # behaviour(state)


# ========
# Clean up
# ========

forcing.close()
out.close()
