#! /usr/bin/env python

import argparse
import logging
import datetime
import os.path

#from .ladim import main

from ladim import main

# ====================
# Parse command line
# ====================

parser = argparse.ArgumentParser(
    description='LADiM — Lagrangian Advection and Diffusion Model')
parser.add_argument(
    '-d', '--debug',
    help="Show more information",
    action="store_const", dest="loglevel", const=logging.DEBUG,
    default=logging.INFO)
parser.add_argument(
    '-s', '--silent',
    help='Show less information',
    action="store_const", dest="loglevel", const=logging.WARNING)
parser.add_argument('config_file', nargs='?', default='ladim.yaml')
args = parser.parse_args()

main(args.config_file, args.loglevel)
