#! /usr/bin/env python

import sys
# from netCDF4 import num2date

from ladim.configuration import Configure
# from gridforce_analytic import Grid, Forcing
from gridforce_discrete import Grid, Forcing
from ladim.release import ParticleReleaser
from ladim.state import State
from ladim.output import OutPut

# ==================
# Initiate the model
# ==================


# --- Configuration ---
if len(sys.argv) > 1:   # configuration file from command line
    config_file = sys.argv[1]
else:
    config_file = 'ladim.yaml'
config = Configure(config_file)

# numsteps = config.numsteps
# dt = config.dt

# --- Initiate the grid and the forcing ---
grid = Grid()
forcing = Forcing(grid)

# --- Initiate particle releaser ---
releaser = ParticleReleaser(config)

#  --- Initiate the model state ---
state = State(config)

# --- Initiate the output ---
out = OutPut(config)
out.write_particle_variables(releaser)

# ==============
# Main time loop
# ==============

for step in range(config.numsteps+1):

    # --- Update forcing ---
    forcing.update(step)

    # --- Particle release ---
    # TODO: Find better name than unique_steps
    if step in releaser.unique_steps:
        V = next(releaser)
        state.append(V)

    # --- Save to file ---
    # Output before update???
    # Have an optional initial output
    if step % config.output_period == 0:
        out.write(state)

    # --- Update the model state ---
    state.update(grid, forcing)

# ========
# Clean up
# ========

forcing.close()
out.close()
